<?php
/**
 * Advanced Custom Fields PRO
 *
 * @author  WP Engine
 *
 * @wordpress-plugin
 * Plugin Name:       Advanced Custom Fields PRO
 * Plugin URI:        https://www.advancedcustomfields.com
 * Description:       Customize WordPress with powerful, professional and intuitive fields.
 * Version:           6.7.1
 * Author:            WP Engine
 * Author URI:        https://wpengine.com/?utm_source=wordpress.org&utm_medium=referral&utm_campaign=plugin_directory&utm_content=advanced_custom_fields
 * Update URI:        https://www.advancedcustomfields.com/pro
 * Text Domain:       acf
 * Domain Path:       /lang
 * Requires PHP:      7.4
 * Requires at least: 6.2
 */

// This file is auto-generated by postinstall.ps1

require_once WPMU_PLUGIN_DIR . '/advanced-custom-fields-pro/acf.php';
