<?php
/**
 * Plugin name: Comet Calendar
 * Description: Centrally manage event information and display it using Comet Components.
 * Author:              Double-E Design
 * Author URI:          https://www.doubleedesign.com.au
 * Version:             0.5.0
 * Requires at least:   6.7.0
 * Requires PHP:        8.4
 * Requires plugins:    advanced-custom-fields-pro, comet-plugin-blocks
 * Text Domain:         comet
 *
 * @package Comet
 */

// This file is auto-generated by postinstall.ps1

require_once WPMU_PLUGIN_DIR . '/comet-calendar/index.php';
