<?php
/**
 * Plugin name: Double-E Design Base Plugin
 * Description: Customisations and common custom functionality for Double-E Design websites.
 *
 * Author:              Double-E Design
 * Author URI:          https://www.doubleedesign.com.au
 * Version:             4.3.2
 * Requires PHP:        8.4
 * Text Domain:         doublee
 * Requires plugins:    advanced-custom-fields-pro
 *
 * @package Doubleedesign\BasePlugin
 */

// This file is auto-generated by postinstall.ps1

require_once WPMU_PLUGIN_DIR . '/doublee-base-plugin/index.php';
