<?php
/**
 * Plugin Name: Double-E TinyMCE
 * Description: Customised configuration and plugins for WordPress/ClassicPress websites by Double-E Design.
 * Requires PHP: 8.4
 * Author: Double-E Design
 * Plugin URI: https://github.com/doubleedesign/doublee-tinymce
 * Author URI: https://www.doubleedesign.com.au
 * Version: 1.0.2
 * Text domain: doublee-tinymce
 */

// This file is auto-generated by postinstall.ps1

require_once WPMU_PLUGIN_DIR . '/doublee-tinymce/index.php';
