if (Test-Path "wordpress") {
	Write-Host "Moving WordPress core into app directory..." -ForegroundColor Cyan
	$source = "wordpress"
	$destination = "app"

	Get-ChildItem -Path $source | ForEach-Object {
		$destPath = Join-Path $destination $_.Name
		if (Test-Path $destPath) {
			Remove-Item -Path $destPath -Recurse -Force
		}
		Move-Item -Path $_.FullName -Destination $destination -Force
	}

	Remove-Item -Path $source -Recurse -Force

	# Check a representative sample of files and directories
	$testFiles = @(
		"app\index.php",
		"app\wp-admin",
		"app\wp-admin\admin.php",
		"app\wp-includes",
		"app\wp-includes\template.php"
	)
	$errors = @()
	foreach ($testFile in $testFiles) {
		if (Test-Path $testFile) {
			Write-Host "Verified: $testFile" -ForegroundColor Green
		}
		else {
			Write-Host "$testFile not found" -ForegroundColor Red
			$errors += $testFile
		}
	}

	if ($errors.Count -gt 0) {
		Write-Host "Error moving WordPress core after composer install or update." -ForegroundColor Red
		exit 1
	}
	else {
		Write-Host "WordPress core moved successfully after composer install or update." -ForegroundColor Green
	}
}

# Move certain plugins from plugins to mu-plugins if they exist in the plugins directory, overwriting existing versions if present
$pluginsToMove = @(
	"advanced-custom-fields-pro",
	"doublee-base-plugin",
	"doublee-tinymce",
	"comet-plugin-blocks",
	"comet-calendar"
)
foreach ($plugin in $pluginsToMove) {
	$source = "app\wp-content\plugins\$plugin"
	$destination = "app\wp-content\mu-plugins\$plugin"

	if (Test-Path $source) {
		if (Test-Path $destination) {
			Write-Host "Removing existing version of $plugin in mu-plugins" -ForegroundColor Yellow
			Remove-Item -Path $destination -Recurse -Force
		}
		Write-Host "Moving $plugin from plugins to mu-plugins" -ForegroundColor Cyan
		Move-Item -Path $source -Destination $destination -Force
	}
}

# Copy the plugin header from the main plugin file to the mu-plugin version if it exists,
# to ensure the metadata (esp. version number) is correct in the admin
foreach ($plugin in $pluginsToMove) {
	$muPluginLoader = "app\wp-content\mu-plugins\$plugin-loader.php"
	$pluginFile = "app\wp-content\mu-plugins\$plugin\index.php";
	if ($plugin -eq "advanced-custom-fields-pro") {
		$pluginFile = "app\wp-content\mu-plugins\$plugin\acf.php"
	}

	if (Test-Path $muPluginLoader) {
		if (Test-Path $pluginFile) {
			Write-Host "Copying plugin header from $pluginFile to $muPluginLoader" -ForegroundColor Cyan
			# Read the plugin file and extract the header comment block (the first comment block in the file)
			$content = Get-Content -Path $pluginFile -Raw
			$headerMatch = [regex]::Match($content, "/\*(.|\s)*?\*/")
			if ($headerMatch.Success) {
				$headerLines = $headerMatch.Value -split "`r?`n"
			}

			$newMuContent = @()
			$newMuContent += "<?php"
			if ($headerLines) {
				$newMuContent += $headerLines
				$newMuContent += ""
			}
			$newMuContent += "// This file is auto-generated by postinstall.ps1"
			$newMuContent += ""
			if ($plugin -eq "advanced-custom-fields-pro") {
				$newMuContent += "require_once WPMU_PLUGIN_DIR . '/$plugin/acf.php';"
			}
			else {
				$newMuContent += "require_once WPMU_PLUGIN_DIR . '/$plugin/index.php';"
			}
			
			Set-Content -Path $muPluginLoader -Value $newMuContent
		}
		else {
			Write-Host "Main plugin file for $plugin not found, skipping metadata copy to mu-plugin loader" -ForegroundColor Yellow
		}
	}
	else {
		Write-Host "Must-use plugin loader for $plugin not found, skipping metadata copy" -ForegroundColor Yellow
	}
}

# Switch ENV back to standard Composer file
$scriptLocation = $PSScriptRoot
$ENV:COMPOSER = "composer.json"

# Handle themes/plugins that need Composer commands run
$themes = Get-ChildItem -Path "app\wp-content\themes" -Directory
$pluginsToComposerUpdate = @(
	"app\wp-content\mu-plugins\doublee-base-plugin",
	"app\wp-content\plugins\doublee-breadcrumbs",
	"app\wp-content\plugins\doublee-ninja-markup",
	"app\wp-content\mu-plugins\doublee-tinymce",
	"app\wp-content\mu-plugins\comet-plugin-blocks"
)
$packagesToUpdate = ($themes | Select-Object -ExpandProperty FullName) + $packagesToComposerUpdate
$devMode = $Env:POWERPRESS_DEV
if ($devMode -eq "1") {
	foreach ($package in $packagesToUpdate) {
		if (Test-Path $package) {
			# If this is a symlinked directory, use its real directory - this helps with path issues when it has its own symlinked dependencies
			$item = Get-Item $package
			if ($item.LinkType -eq "SymbolicLink" -or $item.LinkType -eq "Junction") {
				$package = $item.Target
				Write-Host "Resolved symlink to $( $package )" -ForegroundColor Cyan
			}

			# When processing the Comet Blocks plugin, also ensure the local core package is up-to-date
			if ($package -eq "app\wp-content\plugins\comet-plugin-blocks") {
				$corePath = Join-Path (Split-Path $package -Parent) "core"
				if (Test-Path $corePath) {
					Set-Location $corePath
					try {
						Write-Host "Running composer update for Comet Components Core" -ForegroundColor Cyan
						composer update --prefer-source --no-dev
						composer dump-autoload -o
					}
					catch {
						Write-Host "Error running composer update for Comet Components Core" -ForegroundColor Red
						Write-Host "You might need to run it from its source directory manually to work around symlink issues" -ForegroundColor Yellow
					}
				}
			}

			# Ensure we are in the plugin directory before proceeding
			Set-Location $package

			if (Test-Path (Join-Path $package "composer.local.json")) {
				try {
					$ENV:COMPOSER = "composer.local.json"
					Write-Host "Running composer update with local package config for $package" -ForegroundColor Cyan
					composer update --prefer-source --no-dev
					composer dump-autoload -o

					if (Test-Path "package.json") {
						Write-Host "Running npm install for $package" -ForegroundColor Cyan
						npm install
					}
				}
				catch {
					Write-Host "Error running composer update for $package" -ForegroundColor Red
					Write-Host "You might need to run it from its source directory manually to work around symlink issues" -ForegroundColor Yellow
				}
				finally {
					$ENV:COMPOSER = "composer.json"
					Set-Location $scriptLocation
				}
			}
			else {
				try {
					if (Test-Path "composer.json") {
						Write-Host "Running composer update for $package" -ForegroundColor Cyan
						composer update --prefer-source --no-dev
						composer dump-autoload -o
					}

					if (Test-Path "package.json") {
						Write-Host "Running npm install for $package" -ForegroundColor Cyan
						npm install
					}
				}
				catch {
					Write-Host "Error running composer update for $package" -ForegroundColor Red
					Write-Host "You might need to run it from its source directory manually to work around symlink issues" -ForegroundColor Yellow
				}
				finally {
					Set-Location $scriptLocation
				}
			}
		}
		else {
			Write-Host "$package not found, skipping composer update" -ForegroundColor Yellow
		}
	}
}

Set-Location $scriptLocation
