$prefixes = @("doublee_", "comet_")
$dirRoots = @(".\app\wp-content\plugins", ".\app\wp-content\themes")
$dirPattern = @("doublee-*", "comet-*")
$metaOutputPath = ".\.phpstorm.meta.php"

$dirs = $dirRoots | ForEach-Object {
	$root = $_
	$dirPattern | ForEach-Object { Get-ChildItem -Path $root -Directory -Filter $_ -FollowSymlink }
}

if (-not $dirs -or $dirs.Count -eq 0) {
	Write-Host "No directories found matching the specified patterns." -ForegroundColor Red
	exit 1
}

function Get-PhpFiles {
	param ([string]$Path)
	Get-ChildItem -Path $Path -Recurse -Include *.php -FollowSymlink -ErrorAction SilentlyContinue
}

function Get-Hooks {
	param ([string]$FilePath)

	$pattern = "(apply_filters|do_action)\(\s*['""](" + (($prefixes | ForEach-Object { [regex]::Escape($_) }) -join "|") + ")[^'""]+['""]"

	Select-String -Path $FilePath -Pattern $pattern | ForEach-Object {
		$match = $_.Matches[0]
		[PSCustomObject]@{
			Hook = $match.Value -replace ".*['""]([^'""]+)['""].*", '$1'
			Type = $match.Groups[1].Value
			File = $_.Filename
			Line = $_.LineNumber
		}
	}
}

Write-Host "Scanning directories for PHP files..." -ForegroundColor Cyan
$files = $dirs | ForEach-Object { Get-PhpFiles -Path $_.FullName }

if (-not $files -or $files.Count -eq 0) {
	Write-Host "No PHP files found in matched directories." -ForegroundColor Yellow
	exit 0
}

Write-Host "Extracting hooks from PHP files..." -ForegroundColor Cyan
$hooks = $files | ForEach-Object { Get-Hooks -FilePath $_.FullName }

if (-not $hooks -or $hooks.Count -eq 0) {
	Write-Host "No hooks found matching the specified prefixes." -ForegroundColor Yellow
	exit 0
}

Write-Host "Found $( $hooks.Count ) hook(s):" -ForegroundColor Green
$hooks | Sort-Object Hook -Unique | Format-Table -AutoSize

# Split into actions and filters, deduplicated by hook name
$actions = $hooks | Where-Object { $_.Type -eq "do_action" } |
		Sort-Object Hook -Unique

$filters = $hooks | Where-Object { $_.Type -eq "apply_filters" } |
		Sort-Object Hook -Unique

# Build the argument list strings
function Format-ExpectedArguments {
	param ([string]$FunctionName, [array]$Hooks)

	if (-not $Hooks -or $Hooks.Count -eq 0) {
		return ""
	}

	$args = ($Hooks | ForEach-Object { "        '$( $_.Hook )'" }) -join ",`n"

	return @"
    expectedArguments(
        \$FunctionName(),
        0,
$args
    );
"@
}

$applyFiltersBlock = Format-ExpectedArguments "apply_filters" $filters
$addFilterBlock = Format-ExpectedArguments "add_filter" $filters
$doActionBlock = Format-ExpectedArguments "do_action" $actions
$addActionBlock = Format-ExpectedArguments "add_action" $actions

$metaContent = @"
<?php
/**
 * This file is auto-generated by update-phpstorm-meta.ps1
 * Manual edits will be overwritten by future script runs.
 * Generated: $( Get-Date -Format "yyyy-MM-dd HH:mm:ss" )
 */

namespace PHPSTORM_META {

$applyFiltersBlock

$addFilterBlock

$doActionBlock

$addActionBlock

}
"@

Set-Content -Path $metaOutputPath -Value $metaContent -Encoding UTF8
Write-Host "Meta file written to: $metaOutputPath" -ForegroundColor Green
